version: '3'
services:
  db:
    image: postgres
    env_file:
      - environments/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./django_dir
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_dir:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build:
      context: ./bot_dir
    env_file:
      - environments/bot.env
    depends_on:
      - db
      - web

volumes:
  postgres_data: